language: python
python:
  - '2.7'

before_install:
  - pip install awscli
  - ./travis-install-apex.sh

install:
  - bash install-requirements.sh
  - pip install coveralls

script: coverage run test-setup.py test

after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true

deploy:
- provider: script
  skip_cleanup: true
  script:
  - ./deploy.sh && ./register-modules.sh https://dev-api.door43.org && ./integration_test.sh
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script:
  - ./deploy.sh && ./register-modules.sh https://api.door43.org && ./integration_test.sh
  on:
    branch: master
